- hosts: docker_host
  gather_facts: no

  tasks:
    - name: Remove Container
      docker_container:
        name: java-hello
        state: absent
      ignore_errors: yes

    - name: Create Container
      docker_container:
        name: java-hello
        image: c1t1d0s7/java-hello
        state: started
        recreate: yes
        ports:
          - "8080:8080"
